#!/usr/bin/env node
// Creates a PR on GitHub using a token from GITHUB_TOKEN
const owner = 'Imposter-zx'
const repo = 'Freelance-Web'
const head = 'feature/ci-workflow'
const base = 'main'
const title = 'CI: Add GitHub Actions workflow'
const body = 'CI workflow added to build, lint, and test on push and PRs. Auto-generated by automation.'

const token = process.env.GITHUB_TOKEN
if (!token) {
  console.log('GITHUB_TOKEN is not set. Set it to enable automatic PR creation. Example:\nexport GITHUB_TOKEN=your_token_here')
  process.exit(0)
}

const https = require('https')
const postData = JSON.stringify({ title, head, base, body })

const options = {
  hostname: 'api.github.com',
  path: `/repos/${owner}/${repo}/pulls`,
  method: 'POST',
  headers: {
    'Authorization': `token ${token}`,
    'User-Agent': 'Freelance-Web-CI',
    'Accept': 'application/vnd.github+json',
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(postData)
  }
}

const req = https.request(options, (res) => {
  let data = ''
  res.on('data', chunk => data += chunk)
  res.on('end', () => {
    if (res.statusCode >= 200 && res.statusCode < 300) {
      try {
        const resp = JSON.parse(data)
        console.log('PR created:', resp.html_url)
      } catch {
        console.log('PR created')
      }
    } else {
      console.error('Failed to create PR:', res.statusCode, data)
    }
  })
})
req.on('error', (e) => {
  console.error('Request error:', e)
})
req.write(postData)
req.end()
