param()
{
}

$ErrorActionPreference = 'Stop'

$owner = 'Imposter-zx'
$repo  = 'Freelance-Web'
$head  = 'feature/ci-workflow'
$base  = 'main'
$title = 'CI: Add GitHub Actions workflow'
$body  = 'CI workflow added to build, lint, and test on push and PRs. Auto-generated by automation.'

$token = (Get-ChildItem Env:GITHUB_TOKEN).Value

if ([string]::IsNullOrWhiteSpace($token)) {
  Write-Output 'No GITHUB_TOKEN environment variable found. Please run PR manually at https://github.com/Imposter-zx/Freelance-Web/pull/new/feature/ci-workflow'
  exit 0
}

$headers = @{
  'Authorization' = "token $token"
  'Accept' = 'application/vnd.github+json'
  'User-Agent' = 'Freelance-Web-CI'
}

$payload = @{ title = $title; head = $head; base = $base; body = $body } | ConvertTo-Json
$url = "https://api.github.com/repos/$owner/$repo/pulls"

try {
  $response = Invoke-RestMethod -Method Post -Uri $url -Headers $headers -Body $payload
  Write-Output "PR created: $($response.html_url)"
} catch {
  Write-Error $_.Exception.Message
  exit 1
}
